#!/sbin/runscript
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

#PYNEO_USER="pyneo"

depend() {
	need dbus
	use ofono
}

start() {
	ebegin "Starting pyneod"
	start-stop-daemon --start -m --pidfile /var/run/pyneod.pid \
		--background --quiet --exec /usr/bin/python -- \
		-OO /usr/share/pyneod/pyneod.py
	eend $?
}

stop() {
	ebegin "Stopping pyneod"
	start-stop-daemon --stop --pidfile /var/run/pyneod.pid
	eend $?
}
