#!/sbin/runscript
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	need dbus
}

start() {
	ebegin "Starting gsm0710muxd"
	start-stop-daemon --start --pidfile /var/run/gsm0710muxd.pid \
		--background --quiet --exec /usr/sbin/gsm0710muxd -- \
		-x $SYSFS -s $SERIAL -a 2 -f 100
	eend $?
}

stop() {
	ebegin "Stopping gsm0710muxd"
	start-stop-daemon --stop --pidfile /var/run/gsm0710muxd.pid
	eend $?
}

